/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0/samples
 */

plugins {
    kotlin("jvm") version "1.9.25"
}

group = "io.github.S-furi"
version = "0.0.1-SNAPSHOT"
description = "lsp-project-root"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")
}
